apiVersion: v1
data:
  logstash-snmp.conf: "input {\n  # SNMP MIB-2 System\n  snmp {\n    walk => [\"1.3.6.1.2.1.1\"]\n
    \   hosts => [{host => \"udp:172.20.133.133/161\" community => \"public\"}]\n
    \   interval => 20\n    enable_metric => \"true\"\n  }\n\n  # SNMP MIB-2 Interfaces\n
    \ snmp {\n    walk => [\"1.3.6.1.2.1.2\"]\n    hosts => [{host => \"udp:172.20.133.133/161\"
    community => \"public\"}]\n    interval => 30\n  }\n}\n\n\nfilter {\n    mutate
    {\n      rename =>  { \"host\" => \"host.name\" } \n   }\n}\n\noutput {\n    stdout\n
    \   {\n      codec => rubydebug\n    }\n    #if 'SYSTEM' in [tags] {\n    \telasticsearch
    {\n        \thosts => \"http://134.197.75.32:30549\"\n                data_stream
    => \"true\"\n        \tdata_stream_dataset => \"snmpdevices\"\n    \t}\n}\n\n\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: logstash-snmpconf
  namespace: ccstar
