apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: snmpcollection
  namespace: ccstar
spec:
  selector:
    matchLabels:
      app: snmpcollection # has to match .spec.template.metadata.labels
  serviceName: "snmpcollection"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: snmpcollection # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: snmpcollection
        image: ncar-im-0.rc.unr.edu/imswitchbeat
        args: ["-f", "/etc/logstash/conf.d/logstash-snmp.conf"]
        volumeMounts:
          - name: config
            mountPath: '/etc/logstash/conf.d/'
            readOnly: true
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: config
          configMap:
            name: "logstash-snmpconf" 
            items:
            - key: "logstash-snmp.conf"
              path: "logstash-snmp.conf"
